### ISSUE TITLE
Авторизация при неработающем бэкенде

### ISSUE THREAD

**Issue by annushka-andryushevna** [CarloDiPalma/decks#160]
Исправить, чтобы когда бэкенд лежит, после 3 неудачных попыток загрузиться - выкидывало с сайта

Возможно стоит сделать, чтобы выкидывало сразу, или надо делать "всплывашку"

для всплывашки стоит внедрить react-toastify
https://www.npmjs.com/package/react-toastify

пример всплывашки из figma

![Image](https://github.com/CarloDiPalma/decks/assets/100382249/154169c8-1bda-4ca6-b96c-79f1b1df2ea8)

![Image](https://github.com/CarloDiPalma/decks/assets/100382249/e5152e0d-e528-49f0-997c-b77c7ea49c0d)

**Comment by chepash** [comment]
Исправить, чтобы когда бэкенд лежит, после 3 неудачных попыток загрузиться - выкидывало с сайта
