### ISSUE TITLE
Landing

### ISSUE THREAD

**Issue by chepash** [CarloDiPalma/decks#164]
Запилить нам лэндинг что-то вроде

![Image](https://github.com/CarloDiPalma/decks/assets/100382249/4d8c6eb4-bc86-4b76-8321-a104e04e7dfd)

**Comment by TatsianaKurachova** [comment]
[Ссылка на макет лэндинг](https://www.figma.com/proto/fk3bQMffa43qEgE8vQkiQV/Decks%2FPromo?page-id=0%3A1&type=design&node-id=24-380&viewport=-46%2C357%2C0.1&t=2nirH8n0MDGIGxSB-1&scaling=scale-down-width&starting-point-node-id=24%3A380)

**Comment by chepash** [comment]
В Ветке есть также комиты неоконченных наработок от Артёма и меня (chepash) с настроенными линтерами
